apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kndhvh/api_image:latest
        ports:
        - containerPort: 8000
        resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8000