on:
  push:
    branches:
      - main
jobs: 
  test-job:
    name: Test project
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: Create Docker
          run: make run
        - name: Run tests
          run: make tests


  push_to_registry:
    needs: test-job
    name: Push Docker image to Docker Hub
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_img:latest

  deploy_to_aks:
    needs: push_to_registry
    name: Deploy to AKS
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Install Azure CLI
        run:  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
      - name: Install kubectl
        run:  sudo az aks install-cli

      - name: Log in to Azure
        run : az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password  ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_REC_GROUP}} --name ${{ secrets.AZURE_CLUSTER_NAME }}

      - name: Apply to AKS
        run: kubectl apply -f kubernetes/

      - name: Restart pods
        run: kubectl rollout restart deployment
