name: test
on:
    workflow_run:
        workflows: ["build-test-deploy.yml"]
        types:
            - completed
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "this should not run"