name: deploy
on: push
jobs: 
  test-job:
    name: Test project
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: Create Docker
          run: make run
        - name: Run tests
          run: make tests


  push_to_registry:
    needs: test-job
    name: Push Docker image to Docker Hub
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api_img:latest