name: deploy
on: push
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: Create Docker
          run: make run
        - name: Run tests
          run: make tests
          
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps: 
        - run: echo "hello world"