name: test
on: push
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: Run tests
          run: |
            make run
            make test_api
